GET http://localhost:3001/api/notes/

### 
DELETE http://localhost:3001/api/notes/4

### 
PUT http://localhost:3001/api/notes/5


###
POST http://localhost:3001/api/notes/
content-type: application/json

{
    "content": "This a new note added by post method",
    "important": true
}